### ISSUE TITLE
Properly name classes in Commands

### ISSUE THREAD

**Issue by Xemiru** [MikaalSky/Spongy#1]
_low priority_

The typical convention for Java classes is for the class names to be in [camelCase](http://en.wikipedia.org/wiki/CamelCase), starting with an uppercase letter.

Violating classes:
- com.terminalbit.spongy.command
  - actAsConsole
  - reloadConfig
  - setSpawn
  - setWarp
  - simpleTP
  - simpleTPHERE

Not required, but its nice to follow Java convention.

**Comment by codeHusky** [comment]
I usually follow a lowerUpperUpper kind of thing. I think it looks a bit better, but I might change that in the future.

**Comment by Xemiru** [comment]
usually that's for naming fields unless its a constant; in that case its all uppercase.

do what you wish, but there're a lot of people who're gonna question it if you don't follow the typical conventions
